### ISSUE TITLE
Roadmap to 0.8

### ISSUE THREAD

**Issue by andig** [volkszaehler/mbmd#22]
I feel the current code is already working quite well, though with limited testing and real-world exposure. The things that should be addressed until 0.8 are:

- [ ] allow custom device names using config file
- [ ] rethink the device naming approach (maybe even allow backwards compatibility)
- [x] remove empty connections from API
- [x] remove empty connections from MQTT device names (#34)
- [x] allow specifying query interval (used to be rate limiting) (#59)
- [x] allow closing device connection after query (might help with some SMA devices) (https://github.com/volkszaehler/mbmd/pull/64)
- [x] improve RTU failure handling (re-query last measurement instead of all measurements) (https://github.com/volkszaehler/mbmd/pull/29)
- [x] improve detection against false positives (https://github.com/volkszaehler/mbmd/pull/26 and https://github.com/volkszaehler/mbmd/pull/28)

**Comment by andig** [comment]
See https://github.com/volkszaehler/mbmd/issues/65 for remaining topics
